# Generated by Django 4.1.4 on 2023-01-14 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTrip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False, verbose_name='trip_id')),
                ('from_loc', models.CharField(max_length=30)),
                ('to_loc', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('ret', models.BooleanField(default=False)),
                ('retdate', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
