# Generated by Django 4.1.4 on 2023-01-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        ('travel', '0002_booktrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktrip',
            name='ret',
        ),
        migrations.RemoveField(
            model_name='booktrip',
            name='retdate',
        ),
        migrations.AddField(
            model_name='booktrip',
            name='vehicle',
            field=models.OneToOneField(default='No vehicle Selected', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicle.vehicle'),
        ),
    ]
