# Generated by Django 4.1.4 on 2023-01-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_booktrip_ret_remove_booktrip_retdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktrip',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
