# Generated by Django 4.1.4 on 2023-01-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee1',
        ),
    ]
