# Generated by Django 4.1.4 on 2023-01-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eage',
        ),
    ]
