# Generated by Django 4.1.4 on 2022-12-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsystem', '0002_login_remove_employee_id_alter_employee_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
