# Generated by Django 4.1.4 on 2022-12-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsystem', '0003_alter_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
