# Generated by Django 4.1.4 on 2022-12-29 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsystem', '0005_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsystem.employee'),
        ),
    ]
